eslint enabled and fixed

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -13,6 +13,12 @@ npm run format || (
     false;
 )
 
+#Check ESLint Standards
+npm run lint || (
+       echo -e "$RED\n😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.${NO_COLOR}\n"
+       false;
+)
+
 # If everything passes... Now we can commit
 echo -e "$GREEN\n🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔${NO_COLOR}"
 
